from typing import Dict, List, Optional

# utils.approval
def load_metadata() -> Dict: ...
def save_metadata(data: Dict) -> None: ...
def add_comment(file_id: str, admin: str, comment: str) -> bool: ...
def approve_file(user_folder: str, filename: str, admin: str, comment: Optional[str] = None) -> bool: ...
def reject_file(user_folder: str, filename: str, admin: str, comment: Optional[str] = None) -> bool: ...
def get_pending_files(user_folder: Optional[str] = None) -> List[Dict]: ...

APPROVAL_QUEUE: str = "data/approval_queue"
APPROVED_DB: str = "data/approved/public_db"
METADATA_FILE: str = "data/logs/approvals_metadata.json"

# utils.import_helper
def setup_imports() -> None: ...
def get_project_root() -> str: ...
